server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://project-postgres:5432/projectdb
    username: projectadmin
    password: projectpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
